### ISSUE TITLE
Status of the update/patch get changed in PMT even for SVN client and server related issues

### ISSUE THREAD

**Issue by Ketharan** [wso2-incubator/wso2-patch-signer#41]
**Description:**
Currently the life cycle status of a patch or an update get changed (for example "ready to sign" to "testing") in PMT even for some failures happen in the SVN client or server side (Not relevant to the particular patch or update). That should not happen. The life cycle status of the patch or update should be changed for either any validation issues or at the end of the successful signing. 

**Suggested Labels:**
bug

**Comment by Meruja** [comment]
Fixed with wso2-incubator/wso2-patch-signer/pull/40
