### ISSUE TITLE
Ordering the patches when validating

### ISSUE THREAD

**Issue by Meruja** [wso2-incubator/wso2-patch-signer#8]
**Description:**
When more than two updates come for same product, where one is with small patchID and large time-stamp  and another one with large patchID and smaller time-stamp . Then the update of second patch should go first since the changes of second one needs to be added before the first patch.

**Comment by Meruja** [comment]
The [PR](https://github.com/wso2-incubator/wso2-patch-signer/pull/9) has been sent to resolve it.

**Comment by pramodya1994** [comment]
Fixed in https://github.com/wso2-incubator/wso2-patch-signer/pull/9
